# Generated by Django 2.2.2 on 2020-09-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200911_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='opened',
            new_name='active',
        ),
    ]
