# Generated by Django 2.2.2 on 2020-09-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='listings',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlists', to='auctions.Listing'),
        ),
    ]
